cozy/cozy-mobile

- Cakefile
- www-src/app/application.coffee
- www-src/app/lib/device_status.coffee
- www-src/app/locales/en.coffee
- www-src/app/locales/fr.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_backups.coffee
- www-src/app/service/service_manager.coffee
- www-src/app/views/device_name_picker.coffee
- www-src/app/views/first_sync.coffee
* Fix in WIFi handling : stop backup if wifi connection is lost (and wifi only option is set).
* Fix background service settings transmission : fix "image sync and service may not start".
* Add Error message with install cozy-files on 404 error on files routes.
Label : In progress (wait for new small bugs to fix)
> Small bug fixes

- Cakefile
- www-src/app/locales/en.coffee
- www-src/app/locales/fr.coffee
- www-src/app/replicator/main.coffee
- www-src/app/service/service_manager.coffee
- www-src/app/styles/application.styl
- www-src/app/views/login.coffee
* fix settings for daemon
* add message on login on ssl errors
May be added
* fix issue #40 
* no ssl-check option.
> Smallfixes - daemon, ssl

- config.xml
- www-src/app/replicator/replicator_config.coffee
This PR corresponds to the end of development for 0.1.14 version. Could you tag this version in github repo ?
> Upgrade version from 0.1.13 to 0.1.14

- .codeclimate.yml
see https://codeclimate.com/github/cozy/cozy-mobile/builds/5 and http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml
$ docker run   --interactive --tty --rm   --env CODE_PATH="$PWD"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc   codeclimate/codeclimate validate-config
No errors or warnings found in .codeclimate.yml file.
> Fix code climate configuration

- www-src/app/replicator/replicator_calendars.coffee
> Fix conflict on events.

- www-src/app/lib/android_calendar_helper.coffee
- www-src/app/replicator/main.coffee
- www-src/test/calendars.coffee
* Fix punctual date converted to Android with random timezone (and allday event translating to previous day ...). 
* Fix allday to timed event conversion not working.
> Fixes in cozy --> android events conversion

- Cakefile
- www-src/app/application.coffee
- www-src/app/lib/android_calendar_helper.coffee
Fix typos which hang:
- start service on new pictures
- start app (can't load service/service_manager
Hide alarm type of reminder, not handled on cozy.
> Fix app not starting, Fix newpictures not starting

- www-src/app/templates/permissions.jade
- https://developers.whatwg.org/grouping-content.html#the-p-element
> Fix translation & html syntax

- config.xml
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_config.coffee
This PR corresponds to a new version, so, we have to : 
* Merge development branch in master
* Tags with version 0.1.15
> Upgrade version

- config.xml
- www-src/app/replicator/replicator_config.coffee
Same : https://github.com/cozy/cozy-mobile/commit/fb8f31aea113825bf3761b78f374d762c65197e5
> Upgrade version from 0.1.15 to 0.1.16

- .travis.yml
- coffeelint.json
- www-src/app/application.coffee
- www-src/app/background_service.coffee
- www-src/app/collections/files.coffee
- www-src/app/lib/device_status.coffee
- www-src/app/lib/persistent_log.coffee
- www-src/app/models/contact.coffee
- www-src/app/replicator/design_documents.coffee
- www-src/app/replicator/filesystem.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_backups.coffee
- www-src/app/replicator/replicator_calendars.coffee
- www-src/app/replicator/replicator_config.coffee
- www-src/app/replicator/replicator_contacts.coffee
- www-src/app/replicator/replicator_migration.coffee
- www-src/app/router.coffee
- www-src/app/views/config.coffee
- www-src/app/views/folder.coffee
- www-src/app/views/folder_line.coffee
- www-src/app/views/layout.coffee
- www-src/app/views/notifications.coffee
- www-src/app/views/permissions.coffee
- www-src/package.json
- www-src/test/application.coffee
- www-src/test/assets/_tests.html
- www-src/test/calendars.coffee
- www-src/test/unit/replicator/design_documents.coffee
Ne pas merger avant la prochaine release
> Add coffeelint && fix all lint

- config.xml
- www-src/app/replicator/replicator_config.coffee
This PR corresponds to a new version (0.1.17). We have to :  
* merge development branch in master
* create a new tag
> upgrade version from 0.1.16 to 0.1.17

- .travis.yml
- Cakefile
- README.md
- www-src/app/replicator/filesystem.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_backups.coffee
- www-src/app/templates/layout.jade
Tested on:
* 4.4.2
* 5.0.1
* 5.1.1
* 4.0.4
Additionnal fixes:
* fix photo upload for android pre 4.3 (no BLob(), ...)
* fix debug in chrome desktop
> Update to latest cordova version  5.*

- www-src/app/lib/android_calendar_helper.coffee
- www-src/app/replicator/replicator_calendars.coffee
Please merge https://github.com/cozy/cozy-mobile/pull/136 before this one !
> Remove myCozy  organizer attendee on android created events

- www-src/app/views/config.coffee
Should we extend label to the whole line, making the checkbox easier to toggle (using the whole line instead of only a square around the checkbox ? ping @kelukelu
> Fix tap on checkbox not heard. THanks @kosssi, fix #142 fix #69 .

- www-src/app/lib/android_calendar_helper.coffee
- www-src/app/lib/utils.coffee
- www-src/app/models/contact.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_calendars.coffee
- www-src/app/replicator/replicator_contacts.coffee
- www-src/app/styles/base/_form.styl
- www-src/app/templates/config.jade
- www-src/test/unit/lib/utils.coffee
*  Continue on error on one event or one contact processing
* fix clicking labels in config.
* Remove cal to db.search .
> Continue on error on one event or one contact processing

- www-src/app/replicator/change/change_dispatcher.coffee
- www-src/app/replicator/init.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_config.coffee
- www-src/app/views/config.coffee
Done : 
- fixes in change config scenarios
WIP : 
- accurate error handling in init.
- update init message (first-sync view)
- update backup messages
> Fixes on config update handling.

- www-src/app/lib/persistent_log.coffee
- www-src/app/replicator/init.coffee
- www-src/app/templates/layout.jade
- www-src/app/views/first_sync.coffee
- www-src/app/views/layout.coffee
- www-src/test/unit/replicator/init.coffee
* accurate error handling in init (quit or display message)
* update init message (first-sync view)
> Add subheader message

- www-src/app/background_service.coffee
- www-src/app/replicator/change/change_dispatcher.coffee
- www-src/app/replicator/conflicts_handler.coffee
- www-src/app/replicator/filter_manager.coffee
- www-src/app/replicator/init.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replication_launcher.coffee
- www-src/app/replicator/replicator_backups.coffee
- www-src/app/replicator/replicator_config.coffee
- www-src/test/unit/replicator/filter_manager.coffee
- Reactivate service and update its init states.
- Continue the work of @kosssi in #170 , and fix bidirectionnal filtered replication
- Handle conflicts (for any docTypes)
> Fix push replication, Reactivate service

- config.xml
- www-src/app/replicator/filter_manager.coffee
- www-src/app/replicator/init.coffee
- www-src/app/replicator/main.coffee
- www-src/app/replicator/replicator_backups.coffee
- www-src/app/replicator/replicator_config.coffee
- www-src/app/templates/layout.jade
- www-src/app/templates/permissions.jade
- www-src/app/views/config.coffee
- www-src/app/views/layout.coffee
- www-src/test/unit/replicator/filter_manager.coffee
* Don't hang on no connection on start.
* Don't save config if no connection (and no update filters...)
* Don't bloc in dead end on error in config update and first start .
* Update permission, set migration steps to this version.
> No connection and error handling in config and first start

- src/app/init.coffee
This fix a regression.
When you change your configuration the couch replication filter must be update.
> Update filter when configuration change

- src/app/init.coffee
- src/app/lib/log_sender.coffee
- src/app/templates/first_sync.jade
- src/app/views/config.coffee
- src/app/views/first_sync.coffee
> Add log button when display error in first replication

- src/app/templates/wizard/password.jade
> Fix render html error

- src/app/lib/database.coffee
- src/app/lib/log_sender.coffee
- src/app/replicator/main.coffee
- src/app/views/first_sync.coffee
idb adapter don't exist on Android 4.1
> Fix regression android 4.1

- src/app/replicator/change/change_event_handler.coffee
- src/app/replicator/transformer/cozy_to_android_event.coffee
- src/package.json
- src/test/unit/replicator/transformer/cozy_to_android_event.coffee
I open this issue on cordova plugin https://issues.apache.org/jira/browse/CB-11154
> Fix timezone bug when you edit an event on android

- src/app/templates/config.jade
- src/app/views/config.coffee
The button is not necessary now.
> Remove reset action

- config.xml
- src/app/lib/android_calendar_handler.coffee
- src/app/lib/config.coffee
- src/app/replicator/transformer/cozy_to_android_calendar.coffee
- src/package.json
@nono it's normal that master branch because it's a bugfix
> [BUGFIX] Add default color to calendar

- src/package.json
It's recurring actions after create the release so automate it :smile:
> Move release and display md5 & sha1

- src/app/replicator/change/change_contact_handler.coffee
- src/app/replicator/transformer/cozy_to_android_contact.coffee
> Fix some bugs

- src/app/lib/config.coffee
- src/app/lib/database.coffee
- src/test/unit/lib/database.coffee
I would like to change database on android (to use websql) but it's not good when I create query with startkey and endkey...
> Use websql adapter for iOS

- src/app/lib/media/picture_handler.coffee
Instead of byfullpath it should be byFullPath.
> Fix error because of incorrect case of byFullPath
